[package]
name = "metadata-gen"
version = "0.1.0"
edition = "2018"
publish = false

[[bin]]
name = "metadata-gen"
path = "main.rs"

[dependencies]
contract = { path = "../.." }
serde = "1.0"
serde_json = "1.0"
schemars = "0.8.8"
